/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SallaBreadcrumb {
    }
    interface SallaCheckout {
    }
    interface SallaCheckoutHeader {
    }
}
declare global {
    interface HTMLSallaBreadcrumbElement extends Components.SallaBreadcrumb, HTMLStencilElement {
    }
    var HTMLSallaBreadcrumbElement: {
        prototype: HTMLSallaBreadcrumbElement;
        new (): HTMLSallaBreadcrumbElement;
    };
    interface HTMLSallaCheckoutElement extends Components.SallaCheckout, HTMLStencilElement {
    }
    var HTMLSallaCheckoutElement: {
        prototype: HTMLSallaCheckoutElement;
        new (): HTMLSallaCheckoutElement;
    };
    interface HTMLSallaCheckoutHeaderElement extends Components.SallaCheckoutHeader, HTMLStencilElement {
    }
    var HTMLSallaCheckoutHeaderElement: {
        prototype: HTMLSallaCheckoutHeaderElement;
        new (): HTMLSallaCheckoutHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "salla-breadcrumb": HTMLSallaBreadcrumbElement;
        "salla-checkout": HTMLSallaCheckoutElement;
        "salla-checkout-header": HTMLSallaCheckoutHeaderElement;
    }
}
declare namespace LocalJSX {
    interface SallaBreadcrumb {
    }
    interface SallaCheckout {
    }
    interface SallaCheckoutHeader {
    }
    interface IntrinsicElements {
        "salla-breadcrumb": SallaBreadcrumb;
        "salla-checkout": SallaCheckout;
        "salla-checkout-header": SallaCheckoutHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "salla-breadcrumb": LocalJSX.SallaBreadcrumb & JSXBase.HTMLAttributes<HTMLSallaBreadcrumbElement>;
            "salla-checkout": LocalJSX.SallaCheckout & JSXBase.HTMLAttributes<HTMLSallaCheckoutElement>;
            "salla-checkout-header": LocalJSX.SallaCheckoutHeader & JSXBase.HTMLAttributes<HTMLSallaCheckoutHeaderElement>;
        }
    }
}
